services:
  - type: web
    name: luminai
    env: node
    plan: free
    region: oregon
    buildCommand: |
      cd server && npm install
      cd ../client && npm install && npm run build
      cp -r dist ../server/public
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true

  - type: web
    name: lumin-ai-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    plan: free
    region: oregon
    envVars:
      - key: VITE_API_URL
        value: https://lumin-ai-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
    autoDeploy: true 